# Regenerates _workspace/ACTIVE.md and _workspace/FEATURES.md from per-note frontmatter.
# Source of truth = each note's YAML frontmatter. The script finds its own root via
# $PSScriptRoot, so it needs no per-clone edit; it runs on Windows PowerShell and, via
# pwsh, on macOS/Linux.
#
# Two independent axes:
#   status:  -> ACTIVE.md  (active-work tracker; one row per effort)
#     done/archived/complete/completed -> dropped (terminal)
#     a "resolved" status (see $resolvedStatuses) -> "Resolved" section
#     any other non-empty status        -> "Active work" section
#   feature: -> FEATURES.md (all notes of a feature, grouped by slug; navigation)
#
# A note may carry either key, both, or neither. Terminal status drops a note from
# BOTH indexes. A note with feature: but no status: appears only in FEATURES.md.
# No timestamp in output, so an index changes only when the underlying frontmatter changes.
$ErrorActionPreference = 'Stop'
$root = $PSScriptRoot
if (-not $root -or -not (Test-Path -LiteralPath $root)) { exit 0 }
$wsDir = Join-Path $root '_workspace'
if (-not (Test-Path -LiteralPath $wsDir)) { New-Item -ItemType Directory -Path $wsDir | Out-Null }
$outActive   = Join-Path $wsDir 'ACTIVE.md'
$outFeatures = Join-Path $wsDir 'FEATURES.md'

# "Resolved but not deletable": code-complete + merged, awaiting verification.
$resolvedStatuses = @('verifying','merged-pending-verification','pending-verification')
$terminalStatuses = @('done','archived','complete','completed')

$items = @()
Get-ChildItem -LiteralPath $root -Recurse -Filter *.md -File |
  Where-Object { $_.Name -notin @('ACTIVE.md','FEATURES.md','README.md','DESIGN.md') } |
  ForEach-Object {
    $lines = @(Get-Content -LiteralPath $_.FullName)
    if ($lines.Count -lt 3 -or $lines[0].Trim() -ne '---') { return }
    $end = -1
    for ($i = 1; $i -lt $lines.Count; $i++) { if ($lines[$i].Trim() -eq '---') { $end = $i; break } }
    if ($end -lt 0) { return }
    # Line-based frontmatter parse (not a full YAML parser). Handles scalars,
    # inline arrays (`key: [a, b]`) and multi-line block lists:
    #   key:
    #     - a
    #     - b
    # so Obsidian's Properties editor reformatting an inline array into a block
    # list doesn't silently drop the value. Block items are joined as `a, b` to
    # match the inline-array rendering used downstream.
    $fm = @{}
    $curKey = $null
    for ($i = 1; $i -lt $end; $i++) {
      $line = $lines[$i]
      if ($curKey -and $line -match '^\s*-\s+(.*)$') {
        $item = $Matches[1].Trim().Trim('"',"'")
        $fm[$curKey] = if ($fm[$curKey]) { "$($fm[$curKey]), $item" } else { $item }
      }
      elseif ($line -match '^\s*([A-Za-z0-9_]+):\s*(.*)$') {
        $curKey = $Matches[1]
        $val = $Matches[2].Trim()
        $fm[$curKey] = $val
        if ($val -ne '') { $curKey = $null }   # scalar / inline array; no block list follows
      }
    }
    $get = { param($k,$d) if ($fm.ContainsKey($k)) { $fm[$k].Trim('"',"'") } else { $d } }
    $status = (& $get 'status' '').ToLower()
    if ($status -in $terminalStatuses) { return }   # terminal: drop from both indexes
    $rel = ($_.FullName.Substring($root.Length + 1)) -replace '\\','/'
    $items += [pscustomobject]@{
      Title     = (& $get 'title' $_.BaseName)
      Areas     = ((& $get 'areas' '').Trim('[',']'))
      Status    = $status
      Feature   = ((& $get 'feature' '').Trim('[',']'))
      Updated   = (& $get 'updated' '')
      Resume    = (& $get 'resume' $rel)
      Rel       = $rel
      Resolved  = ($status -in $resolvedStatuses)
    }
  }

$items = @($items | Sort-Object @{Expression='Updated';Descending=$true}, Title)

# Shared clickable markdown link (filename text, ../-relative from _workspace/).
$mdLink = { param($rel) $leaf = ($rel -split '/')[-1]; "[$leaf](../$rel)" }

# ---- ACTIVE.md ----
$sb = [System.Collections.Generic.List[string]]::new()
$sb.Add('<!-- GENERATED by regen-active.ps1 from per-note frontmatter. Do not edit by hand. -->')

$emit = {
  param($heading, $rows)
  $sb.Add($heading)
  $sb.Add('')
  if ($rows.Count -eq 0) {
    $sb.Add('_(none)_')
  } else {
    foreach ($it in $rows) {
      $head = @("**$($it.Title)**")
      if ($it.Areas) { $head += $it.Areas }
      $head += "status: $($it.Status)"
      if ($it.Updated) { $head += "updated: $($it.Updated)" }
      $sb.Add('- ' + ($head -join ' · '))
      $sb.Add("  doc: $(& $mdLink $it.Rel) · resume: ``$($it.Resume)``")
    }
  }
}

$activeItems = @($items | Where-Object { $_.Status })
& $emit '# Active work' @($activeItems | Where-Object { -not $_.Resolved })
$sb.Add('')
& $emit '# Resolved — pending verification' @($activeItems | Where-Object { $_.Resolved })
Set-Content -LiteralPath $outActive -Value ($sb -join "`n") -Encoding utf8

# ---- FEATURES.md ----
$fsb = [System.Collections.Generic.List[string]]::new()
$fsb.Add('<!-- GENERATED by regen-active.ps1 from per-note frontmatter. Do not edit by hand. -->')
$fsb.Add('# By feature')
$fsb.Add('')
$featItems = @($items | Where-Object { $_.Feature })
if ($featItems.Count -eq 0) {
  $fsb.Add('_(none)_')
} else {
  $groups = @{}
  foreach ($it in $featItems) {
    foreach ($slug in ($it.Feature -split ',')) {
      $s = $slug.Trim()
      if (-not $s) { continue }
      if (-not $groups.ContainsKey($s)) { $groups[$s] = @() }
      $groups[$s] += $it
    }
  }
  $orderedSlugs = @($groups.Keys | Sort-Object @{Expression={ @($groups[$_].Updated | Sort-Object -Descending)[0] }; Descending=$true}, @{Expression={$_}})
  foreach ($slug in $orderedSlugs) {
    $members = @($groups[$slug] | Sort-Object @{Expression='Updated';Descending=$true}, Title)
    $areas = @($members.Areas | Where-Object { $_ } |
               ForEach-Object { $_ -split ',' } | ForEach-Object { $_.Trim() } |
               Where-Object { $_ } | Select-Object -Unique)
    $headParts = @("## $slug")
    if ($areas.Count) { $headParts += ($areas -join ', ') }
    $fsb.Add($headParts -join ' · ')
    foreach ($it in $members) {
      $seg = @(& $mdLink $it.Rel)
      if ($it.Status)  { $seg += $it.Status }
      if ($it.Updated) { $seg += $it.Updated }
      $fsb.Add('- ' + ($seg -join ' · '))
    }
    $fsb.Add('')
  }
}
Set-Content -LiteralPath $outFeatures -Value ($fsb -join "`n") -Encoding utf8
